### PR TITLE
I want to push the md file from my local repository

### PR DESCRIPTION
**Pull request by SamsonKwizela**
I have read through and I have created my md file which i want to push to this repo in response to the assignment.

### CODE REVIEW

**Comment by OlivierJM** [comment]
@SammyLoyalty this is the wrong PR, The correct one is the one you used pa first, this is mine only use the one that your username in the title. 
Also please have a single Github account I see 2: 

- @Sammy-Loyaty-Tech 
- @SammyLoyalty

**Comment by SamsonKwizela** [comment]
I don’t know how this is happening, I don’t even remember the other
accounts.. I have noticed that I have two repositories, one has the content
of my work and the other one has nothing. It’s confusing me, could it mean
I have accepted the assignment twice ?

**Comment by OlivierJM** [comment]
> I don’t know how this is happening, I don’t even remember the other accounts.. I have noticed that I have two repositories, one has the content of my work and the other one has nothing. It’s confusing me, could it mean I have accepted the assignment twice ?

I don't think it is the assignment, It seems like there's definitely 2 separate accounts Just choose one and stick to it.

**Comment by ghost** [comment]
I think I only have one account, so should I move my work to the other
account?

**Comment by SamsonKwizela** [comment]
I have seen, the one which has a name @Sammy-Loyaty-Tech  I don’t use it, created the other one when I was told not to use the school email

**Comment by SamsonKwizela** [comment]
How is that I’m using both at the same time 😭😭 without knowing

**Comment by OlivierJM** [comment]
Maybe you set it as your computer git username in the git config and when you push that's the one that reflects, I am not sure.

**Pull request closed without merging**
